// GLOBAL
export const EL_REQUEST = 'EL_REQUEST';
export const EL_SUCCESS = 'EL_SUCCESS';
export const EL_FAILURE = 'EL_FAILURE';

export const SEL_REQUEST = 'SEL_REQUEST';
export const SEL_SUCCESS = 'SEL_SUCCESS';
export const SEL_FAILURE = 'SEL_FAILURE';

export const ISAUTHENTICATED_REQUEST = 'ISAUTHENTICATED_REQUEST';
export const ISAUTHENTICATED_SUCCESS = 'ISAUTHENTICATED_SUCCESS';
export const ISAUTHENTICATED_FAILURE = 'ISAUTHENTICATED_FAILURE';

// ADMINS
export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const GET_ADMIN_FAILURE = 'GET_ADMIN_FAILURE';

// USERS
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// ROLES
export const GET_ROLE_REQUEST = 'GETROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GETROLE_SUCCESS';
export const GET_ROLE_FAILURE = 'GETROLE_FAILURE';

// TYPES
export const GET_TYPE_REQUEST = 'GET_TYPE_REQUEST';
export const GET_TYPE_SUCCESS = 'GET_TYPE_SUCCESS';
export const GET_TYPE_FAILURE = 'GET_TYPE_FAILURE';

// CONFIGURATIONS
export const GET_CONFIGURATION_REQUEST = 'GET_CONFIGURATIONS_REQUEST';
export const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATIONS_SUCCESS';
export const GET_CONFIGURATION_FAILURE = 'GET_CONFIGURATIONS_FAILURE';

// PERMISSIONS
export const GET_PERMISSION_REQUEST = 'GET_PERMISSIONS_REQUEST';
export const GET_PERMISSION_SUCCESS = 'GET_PERMISSIONS_SUCCESS';
export const GET_PERMISSION_FAILURE = 'GET_PERMISSIONS_FAILURE';

// SYMBOLS
export const GET_SYMBOL_REQUEST = 'GET_SYMBOLS_REQUEST';
export const GET_SYMBOL_SUCCESS = 'GET_SYMBOLS_SUCCESS';
export const GET_SYMBOL_FAILURE = 'GET_SYMBOLS_FAILURE';

// GROUPS
export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAILURE = 'GET_GROUP_FAILURE';




