// GLOBAL
export const EL_REQUEST = 'EL_REQUEST';
export const EL_SUCCESS = 'EL_SUCCESS';
export const EL_FAILURE = 'EL_FAILURE';

export const SEL_REQUEST = 'SEL_REQUEST';
export const SEL_SUCCESS = 'SEL_SUCCESS';
export const SEL_FAILURE = 'SEL_FAILURE';

export const ISAUTHENTICATED_REQUEST = 'ISAUTHENTICATED_REQUEST';
export const ISAUTHENTICATED_SUCCESS = 'ISAUTHENTICATED_SUCCESS';
export const ISAUTHENTICATED_FAILURE = 'ISAUTHENTICATED_FAILURE';

// ADMINS
export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const GET_ADMIN_FAILURE = 'GET_ADMIN_FAILURE';

// USERS
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// ROLES
export const GET_ROLE_REQUEST = 'GETROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GETROLE_SUCCESS';
export const GET_ROLE_FAILURE = 'GETROLE_FAILURE';

// TYPES
export const GET_TYPE_REQUEST = 'GET_TYPE_REQUEST';
export const GET_TYPE_SUCCESS = 'GET_TYPE_SUCCESS';
export const GET_TYPE_FAILURE = 'GET_TYPE_FAILURE';

// CONFIGURATIONS
export const GET_CONFIGURATION_REQUEST = 'GET_CONFIGURATIONS_REQUEST';
export const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATIONS_SUCCESS';
export const GET_CONFIGURATION_FAILURE = 'GET_CONFIGURATIONS_FAILURE';

// PERMISSIONS
export const GET_PERMISSION_REQUEST = 'GET_PERMISSIONS_REQUEST';
export const GET_PERMISSION_SUCCESS = 'GET_PERMISSIONS_SUCCESS';
export const GET_PERMISSION_FAILURE = 'GET_PERMISSIONS_FAILURE';

// MANAGERS
export const GET_MANAGER_REQUEST = 'GET_MANAGER_REQUEST';
export const GET_MANAGER_SUCCESS = 'GET_MANAGER_SUCCESS';
export const GET_MANAGER_FAILURE = 'GET_MANAGER_FAILURE';

// MT5 MANAGERS
export const GET_MT5MANAGER_REQUEST = 'GET_MT5MANAGER_REQUEST';
export const GET_MT5MANAGER_SUCCESS = 'GET_MT5MANAGER_SUCCESS';
export const GET_MT5MANAGER_FAILURE = 'GET_MT5MANAGER_FAILURE';

// COVERAGESERVERS
export const GET_COVERAGESERVER_REQUEST = 'GET_COVERAGESERVER_REQUEST';
export const GET_COVERAGESERVER_SUCCESS = 'GET_COVERAGESERVER_SUCCESS';
export const GET_COVERAGESERVER_FAILURE = 'GET_COVERAGESERVER_FAILURE';

// COVERAGEACCOUNTS
export const GET_COVERAGEACCOUNT_REQUEST = 'GET_COVERAGEACCOUNT_REQUEST';
export const GET_COVERAGEACCOUNT_SUCCESS = 'GET_COVERAGEACCOUNT_SUCCESS';
export const GET_COVERAGEACCOUNT_FAILURE = 'GET_COVERAGEACCOUNT_FAILURE';

// MT5SYMBOL
export const GET_MT5SYMBOL_REQUEST = 'GET_MT5SYMBOL_REQUEST';
export const GET_MT5SYMBOL_SUCCESS = 'GET_MT5SYMBOL_SUCCESS';
export const GET_MT5SYMBOL_FAILURE = 'GET_MT5SYMBOL_FAILURE';

// SYMBOL
export const GET_SYMBOL_REQUEST = 'GET_SYMBOL_REQUEST';
export const GET_SYMBOL_SUCCESS = 'GET_SYMBOL_SUCCESS';
export const GET_SYMBOL_FAILURE = 'GET_SYMBOL_FAILURE';

// SUFFIX
export const GET_SUFFIX_REQUEST = 'GET_SUFFIX_REQUEST';
export const GET_SUFFIX_SUCCESS = 'GET_SUFFIX_SUCCESS';
export const GET_SUFFIX_FAILURE = 'GET_SUFFIX_FAILURE';



